### ISSUE TITLE
U Enhance Newsletter History Page

### ISSUE THREAD

**Issue by gabrielsaruhashi** [AmeelioDev/letters#103]
Right now, we are not displaying a whole lot of info for the newsletter history page. Let's give admins visibility over the newsletter that they sent.

**Task List**
- [ ] Add cards with breakdown of the different letter status
- [ ] Add header with file name (and URL), date and total cost
- [ ] Add tracker listing letters sent to all contacts in different facilities

![newsletter_history](https://user-images.githubusercontent.com/12942772/83550868-e54d5680-a4dd-11ea-8c7b-290c416e390b.png)
